import type { Metadata } from "next";
import { Inter, Quicksand } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="max-sm:text-[12px] max-xl:text-[14px] text-[16px]"
    >
      <body className={`${quicksand.variable}`}>
        <main className="flex min-h-screen flex-col items-center justify-between bg-gray-50 font-quicksand">
          {children}
        </main>
      </body>
    </html>
  );
}
